### PR TITLE
fixed critical issue in copying large files

### PR DESCRIPTION
**Pull request by l3utterfly**
Critical issue in android for copying large files: previous version downloads the large file but does not copy anything over 2GB.

Sorry! This PR fixes it.

### CODE REVIEW

**Comment by kesha-antonov** [comment]
Is it working on android 7.0?

**Comment by kesha-antonov** [comment]
https://developer.android.com/reference/java/nio/file/package-summary

Added in [API level 26](https://developer.android.com/guide/topics/manifest/uses-sdk-element#ApiLevels)
java.nio.file

I previously added this API but changed to FileChannel because we need to support android 7.0+ (api 24+)

**Comment by l3utterfly** [comment]
Hmm.. my app has min version 26 so this was not a problem.

How about this code?
```
private static void moveFile(File src, File dst) throws IOException {
    FileChannel inChannel = new FileInputStream(src).getChannel();
    FileChannel outChannel = new FileOutputStream(dst).getChannel();
    try {
        long bytesTransferred = 0;
        long totalBytes = inChannel.size();
        while (bytesTransferred < totalBytes) {
            long remainingBytes = totalBytes - bytesTransferred;
            long chunkSize = Math.min(remainingBytes, Integer.MAX_VALUE);
            long transferredBytes = inChannel.transferTo(bytesTransferred, chunkSize, outChannel);
            bytesTransferred += transferredBytes;
        }
        src.delete();
    } finally {
        if (inChannel != null)
            inChannel.close();
        if (outChannel != null)
            outChannel.close();
    }
}
```
(untested, but should work). The main problem with the previous code is that `transferTo` takes an `Int`, which cannot go past 2GB

**Comment by kesha-antonov** [comment]
Could you test in android emulator with api 24?

I can do it also but on Wednesday.

**Comment by Prashant13Pawar** [comment]
Not able to download files above 1GB . Please provide fix for this

**Comment by l3utterfly** [comment]
Did you try the code in the PR? I tested it and it works for files over 4GB with no problems

**Comment by Prashant13Pawar** [comment]
I tried code from PR still same issue

**Comment by l3utterfly** [comment]
Hmm.. not sure, will take a look later. The code works fine, and it is already in production, so not sure what's wrong with your version

**Comment by sjchristi** [comment]
this fix worked great in my app.  using now in production.  thank you very much.

**Comment by HyopeR** [comment]
@sjchristi 
Are you using the version in this pull request? https://github.com/kesha-antonov/react-native-background-downloader/pull/20 
If you find any crashes, please give feedback.
I have been observing it for 2-3 weeks on a production project and everything is going well.

It should also solve this problem that you opened before. Have you tested it? **"Downloader breaking every other time you reload in debugger"**

**Comment by sjchristi** [comment]
> @sjchristi Are you using the version in this pull request? #20 If you find any crashes, please give feedback. I have been observing it for 2-3 weeks on a production project and everything is going well.
> 
> It should also solve this problem that you opened before. Have you tested it? **"Downloader breaking every other time you reload in debugger"**

I have not tested PR #20 yet.  I'm just using [l3utterfly](https://github.com/l3utterfly)'s fork at the moment.  Does #20 include the fixes in this PR?  I can switch over and test that as well.

**Comment by kesha-antonov** [comment]
I'll close this for now since we've merged @HyopeR PR that should have fixes

If it doesn't fix this issue, we'll reopen it

**Pull request closed without merging**
